services:
  angie:
    image: docker.angie.software/angie:latest
    container_name: angie
    volumes:
      - $PWD/angie.conf:/etc/angie/angie.conf
      - $PWD/options-ssl-angie.conf:/etc/angie/options-ssl-angie.conf
      - 3x-ui-aio-volume:/var/lib/angie/acme/
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    restart: unless-stopped
    networks:
      - 3x-ui-aio-network

  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    volumes:
      - 3x-ui-aio-volume:/etc/x-ui/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      X_UI_ENABLE_FAIL2BAN: "false"
    tty: true
    restart: unless-stopped
    networks:
      - 3x-ui-aio-network

  authorization-stub:
    image: ampetelin/authorization-stub
    container_name: authorization-stub
    environment:
      HOST: "0.0.0.0"
      PORT: "5000"
    restart: unless-stopped
    networks:
      - 3x-ui-aio-network

  warp-socks:
    image: monius/docker-warp-socks:latest
    container_name: warp-socks
    ports:
      - "9091:9091"
      # - target: 9091
      #   published: 9091
      #   mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv4.conf.all.src_valid_mark: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "https://www.cloudflare.com/cdn-cgi/trace"]
      interval: 30s
      timeout: 10s
      retries: 5
    #restart: on-failure
    restart: unless-stopped
    networks:
      - 3x-ui-aio-network
      
networks:
  3x-ui-aio-network:
    name: 3x-ui-aio-network

volumes:
  3x-ui-aio-volume:
    name: 3x-ui-aio-volume
